### PR TITLE
docs: Added a diagram directory

### PR DESCRIPTION
**Pull request by ahitacat**
Added this directory to tack the protocol diagrams. 

Initial diagrams added
- Connection
- Data message Echo worker
- Cancel message Echo worker

Github provides a pre-view of mermaid diagrams. To see it go to the forked repo https://github.com/ahitacat/yggdrasil/tree/doc-init-diagrams/doc/diagrams

### CODE REVIEW

**Comment by ahitacat** [comment]
@subpop @jirihnidek Do you think there are some diagram missing?

**Review by jirihnidek — APPROVED** [review]
LGTM

**Comment by jirihnidek** [comment]
I think that this PR is ready for review.

**Review by subpop — APPROVED** [review]
This looks good to me.

**Pull request merged**
